---

- name: yum | mig dependencies install
  yum: name={{ mig_scheduler_pkgs }} state=present update_cache=yes

- name: yum | Ensure haveged is running and enabled on boot.
  service: name=haveged state=started enabled=yes

## default configuration file on centos include http server which would conflict with ours
#- file: dest=/etc/nginx/nginx.conf state=absent
#  when: mig_nginx_use_ssl is defined and not mig_nginx_use_ssl
#- file: src=/etc/nginx/conf.d/mig.conf dest=/etc/nginx/nginx.conf state=link force=yes
#  when: mig_nginx_use_ssl is defined and not mig_nginx_use_ssl
#  notify:
#    - restart nginx

- template: src=nginx-default-centos.conf.j2 dest=/etc/nginx/nginx.conf mode=0644 force=yes backup=yes
  when: mig_nginx_use_ssl is defined and not mig_nginx_use_ssl
  notify:
    - restart nginx
